version: '3.8'
services:
    front-nginx:
        build:
            context: ../
            dockerfile: docker-env/front-nginx/Dockerfile
        container_name: front-nginx
        restart: always
        ports:
            - "80:80"
        command: nginx -g 'daemon off;'
